spring:
  datasource:
    druid:
      master:
        name: masterDB
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/orjrs?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: mysql15720 #mysql版本号

      slave:
        name: slaveDB
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/orjrs?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: mysql15720 #mysql版本号
mybatis:
  config-location: classpath:mybatis-config.xml